; SCSA-16 PSI/O Firmware - Fixed Boot Segment (0xF000)
; This file is conceptual. The actual machine code is generated by the emulator dynamically.

.ORG 0xF000     

; Successful Boot: The emulator writes: JMP 0x0100

; Failed Boot: The emulator writes: HLT (0x00 0x00 0x00)
; This triggers the PSI/O Shell, which runs diagnostics and waits for 'load' command.

HLT             ; Placeholder HLT instruction in the source code
